# Generated by Django 5.0.6 on 2024-06-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travel",
            name="term",
            field=models.IntegerField(),
        ),
    ]
