# Generated by Django 5.0.6 on 2024-06-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0002_alter_travel_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travel",
            name="hotel",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="hotel.hotel"
            ),
        ),
        migrations.AlterField(
            model_name="travel",
            name="klass",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="hotel.klass"
            ),
        ),
    ]
